version: '3.7'

services:
  db:
    image: postgres:17
    container_name: db_app
    command: -p 5432
    expose:
      - 5432

  app:
    build:
      context: .
    container_name: fastapi_url_shortener
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
